name: delivery_app
description: Aplicativo de entregas para clientes e motoristas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.1
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  sqflite: ^2.3.2
  path: ^1.9.0
  url_launcher: ^6.2.5
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
