spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos


spring.datasource.username=anaflavia_apsis
spring.datasource.password=galodoido

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.locations=classpath:db/migration
